### ISSUE TITLE
Packagist support?

### ISSUE THREAD

**Issue by hassankhan** [thephpleague/skeleton#10]
Could this repository be put up on Packagist so I could just type in `composer create-project league/skeleton`?

**Comment by reinink** [comment]
I'm not sure this makes sense, as this is meant more as an internal tool for us. It's not an actual package. For what it's worth, it doesn't take too much more to do this with Git:

```
git clone https://github.com/thephpleague/skeleton.git .
```

**Comment by frankdejonge** [comment]
@reinink I'd like to reconsider this. It's a nice way get started, one off command. No git history, while initially meant for internal use. The external use cases are certainly there.

**Comment by taylorotwell** [comment]
Yeah I agree. I would suggest taking some of the League branding off it in terms of the default League namespace and such. That would make this a great, standard way to get a basic package structure up and running in a few minutes.

**Comment by taylorotwell** [comment]
Although I can see the benefit to you internally I guess of having it League branded for your own speed of development.

**Comment by hassankhan** [comment]
You could always add another parameter to find-and-replace.

**Comment by philsturgeon** [comment]
Yup the vendor namespace should be configurable like anything else.

**Comment by frankdejonge** [comment]
I've had a chat with @assertchris yesterday, who showed me a nice implementation of this and a little more. He'll be working out some of the details there get this in line with the current skeleton package. Right Chris?

**Comment by assertchris** [comment]
verily!

**Comment by soleo** [comment]
How about https://www.npmjs.com/package/generator-php-pacakage? Generate a skeleton with yeoman
