### ISSUE TITLE
PHPUnit 6 does not work with the default ExampleTest

### ISSUE THREAD

**Issue by alnutile** [thephpleague/skeleton#114]
## Detailed description

PHPUnit 6 wants `PHPUnit\Framework\TestCase`
but the default file has `extends \PHPUnit_Framework_TestCase`
so if `composer install` installs 6 per the composer.json options `~4.0||~5.0||~6.0`
then this will break.
## Context
Not sure the best solution. The user might not run `composer install` prior to running the `prefill` file so hard to fix it during setup.

## Possible implementation

Maybe update the docs? I am happy to provide a fix just not sure the best way to go with it.

## Your environment

 * PHP 5.6

**Comment by frankdejonge** [comment]
I'd say we can move away from version 4.0. If I'm not mistaken 5.0 supplies both the `_`'d class and the namespaced one, so we can just move to the namespaced one.

**Comment by alnutile** [comment]
thanks for the fix @ozh
