### ISSUE TITLE
Scrutinizer and code coverage

### ISSUE THREAD

**Issue by Jeroen-G** [thephpleague/skeleton#26]
I used the .scrutinizer.yml file of this Skeleton. When I run an inspection on scrutinizer-ci, it times out because of the long waiting for 'external code coverage' which then ends in "Code coverage data is not yet available."
Is there something I did wrong?

**Comment by assertchris** [comment]
remove these lines: https://github.com/thephpleague/skeleton/blob/2da424a3f7b94f9ca5ac9e412d1418509dcd9074/.scrutinizer.yml#L20-L22
or set up travis to send the coverage data to scruitinzer: https://github.com/thephpleague/skeleton/blob/2da424a3f7b94f9ca5ac9e412d1418509dcd9074/.travis.yml#L14-L18

**Comment by Jeroen-G** [comment]
Thanks a lot!
