### ISSUE TITLE
make `skeleton` vendor agnostic

### ISSUE THREAD

**Issue by browner12** [thephpleague/skeleton#53]
would you be open to a PR that replaces references to `thephpleague` and `league` with a generic `:vendor` placeholder? This would make the package more agnostic and serve as a good starting point for all packages.

**Comment by vjandrea** [comment]
:+1:

**Comment by browner12** [comment]
thanks @vjandrea for drawing my attention back to this. can we get a maintainer to comment quick? the fix would be relatively quick, just want to know if it's something that would be accepted.

**Comment by TUNER88** [comment]
+1
