### ISSUE TITLE
Commit to drop 5.4 introduced a bug in travis that makes build fail with an error

### ISSUE THREAD

**Issue by ibrahimlawal** [thephpleague/skeleton#67]
This commit: [drop PHP 5.4](https://github.com/thephpleague/skeleton/commit/bd4f085b9158dbd30b9745467db10328fdf3a10c) should have also changed matrix php setting to 5.5. This caused errors when building on travis:

This package requires php ~5.5|~7.0 but your PHP version (5.4.37) does not satisfy that requirement.

**Comment by philsturgeon** [comment]
Resolved in #68.

Thanks for this! If you have a solution feel free to save yourself a little time by just sending the PR and not doing the issue to. I usually use the issue first then PR later approach only when I'm not sure if I'll actually get a fix in in a reasonable time. :)
