### ISSUE TITLE
Rationale behind separate namespace for tests

### ISSUE THREAD

**Issue by sanmai** [thephpleague/skeleton#71]
What is a rationale behind creating a separate namespace for tests as seen in [tests/ExampleTest.php](https://github.com/thephpleague/skeleton/blob/master/tests/ExampleTest.php)? 

E.g. why one should use `League\Skeleton\Test` but not `League\Skeleton` for his `ExampleTest`?

How that approach is supposed to work for deeper namespaces? E.g. for `League\Skeleton\Deep\EvenDeeper`

**Comment by kamilsk** [comment]
To exclude tests from stable package https://github.com/thephpleague/skeleton/blob/master/composer.json#L32-L36 -> https://github.com/thephpleague/skeleton/blob/master/.gitattributes#L10

And simplest configuration of PHPUnit https://github.com/thephpleague/skeleton/blob/master/phpunit.xml.dist#L12-L16 (compare with https://github.com/symfony/symfony/blob/master/phpunit.xml.dist#L20-L27)

IMO

> How that approach is supposed to work for deeper namespaces? E.g. for `League\Skeleton\Deep\EvenDeeper`

`League\Skeleton\Deep\EvenDeeper ` -> `League\Skeleton\Test\Deep\EvenDeeper `

But, I use something else: https://github.com/kamilsk/CilexServiceProviders/blob/master/composer.json#L41, ie prefix, not postfix

**Comment by sanmai** [comment]
How does a namespace helps to exclude tests from stable package? How does a namespace (not a directory) simplify testing configuration? 

If you omit it altogether, everything will be even simpler.

Why do you even need to mention `Test` in a namespace if every class is already prefixed with `Test`?

**Comment by kamilsk** [comment]
> How does a namespace helps to exclude tests from stable package?

I gave the logical chain by the example.

> How does a namespace (not a directory) simplify testing configuration?

This is a logical consequence of the example above.

> How does a namespace (not a directory)

http://www.php-fig.org/psr/psr-4/#2-specification paragraph `3.2`

It is accepted convention, but you can use something of your own in your own project (if you like [Go Lang Way](https://golang.org/doc/code.html#Testing) use it).

**Comment by sanmai** [comment]
Closed by #72
