### ISSUE TITLE
"docs" entry in .gitignore?

### ISSUE THREAD

**Issue by jotaelesalinas** [thephpleague/skeleton#87]
Shouldn't "docs" be in `.gitattributes` instead of `.gitignore`?

This way, the documentation would be available in the repository for everybody to read but it would not be downloaded when the package is required by another project.

**Comment by yuloh** [comment]
It looks like that was added before you could put the github docs in `./docs`.  I'm not sure what it was excluding since everyone has their docs in a different branch.

**Comment by reinink** [comment]
Yes, @yuloh is correct. This should be removed now. To be honest I'm not sure why that was even in there to start.
